### ISSUE TITLE
Use authorized_keys instead of password?

### ISSUE THREAD

**Issue by elgalu** [NVIDIA/deepops#1000]
https://github.com/NVIDIA/deepops/blob/cedc7f2adba4cd049d945fca12d94d00ae780e87/config.example/group_vars/all.yml#L100-L102

Hi, for access management, how would you recommend using ssh authorized_keys instead of passwords in this project?

**Comment by ajdecon** [comment]
We use this role for user management: https://github.com/DeepOps/ansible-role-users

It supports adding an `ssh_key` field to each user with a list of public keys, e.g.

```
 - username: nvidia 
   name: nvidia 
   ssh_key:
   - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCzDYWb0MjHeVM..."
   - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCzDYWb0FSNDJF..."
```

We don't include this in the default example config, because an example password hash is more usable than a pubkey without the associated private key. 😄 However we should probably put an example of this in the comments of `all.yml`.
