### ISSUE TITLE
k8s-gpu-plugin.yml - throws syntax error

### ISSUE THREAD

**Issue by phogan-nvidia** [NVIDIA/deepops#112]
Trying deepops-refacor branch on Centos7 before bring to the customer - any insight on the issue below being really a syntax issue or actually OS related. 

Install Process
Install a supported operating system (Ubuntu/RHEL)

```
$ ansible-playbook -v -i k8s-config/hosts.ini -b playbooks/k8s-cluster.yml
Using /home/deepops/deepops-refactor/ansible.cfg as config file

ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/home/deepops/deepops-refactor/playbooks/k8s-gpu-plugin.yml': line 17, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

        name: openshift
    - name: create GPU device plugin
      ^ here


```
k8s-gpu-plugin.yml
```
---

- hosts: kube-master
  become: true
  become_method: sudo
  tasks:
    - name: install pip
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - "python-pip"
      when: (ansible_facts['distribution'] == 'Ubuntu')
    - name: install openshift python client for k8s_raw module
      pip:
        name: openshift
    - name: create GPU device plugin
      k8s:
        state: present
        definition: "{{ lookup('url', 'https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/v1.12/nvidia-device-plugin.yml', split_lines=False) }}"
      run_once: true
  tags:
    - k8s_gpu_device_plugin
```
