### ISSUE TITLE
Wrong scope in roles/slurm/tasks/login-compute-setup.yml

### ISSUE THREAD

**Issue by chschulze** [NVIDIA/deepops#1170]
roles/slurm/tasks/login-compute-setup.yml defines a wrong scope.

In both tasks it should be:
when: is_compute

instead of:

when: is_controller

At least for me the change made it work as expected. Should be an easy fix.

Thanks

**Comment by avolkov1** [comment]
There are two tasks there. One task hides GPUs in ssh sessions on controller node. The other task makes it so that not everything related to users' processes are killed on controller node (otherwise the user is logged off after a job ends). These are only needed on controller node. In single node setup controller node and compute node are the same. But I've set this up with multiple nodes where there are multiple compute nodes, but only one of them is also a controller node, and these operations need to be done on the controller node, but not other compute nodes.

So it would be fine to set `is_compute` if doing strictly a single node, but `is_controller` will also work and apply for multi-node setups. I've set this up with multiple nodes, up to about 6 nodes and then it's important to differentiate.

I think maybe you just probably didn't re-run the playbook setup. At one point the playbook informs the user to reboot manually. Afterwards the user is supposed to run the playbook again. Typically I'll run it at least 3 times.

1. First time until reboot.
2. Second time continue after reboot.
3. Third time just to check that Ansible ran everything as it should skip most tasks, but occasionally maybe something didn't run/finish successfully and running the playbook a third time deals with these anomalies.

I understand it made it work, but the other way should have worked too, just need to run the playbook several times as is typically required.

**Comment by chschulze** [comment]
Ok, thanks for the reply. I'm running a setup with multiple compute nodes. I made the change to the mentioned file as otherwise the ssh login to the compute nodes during running jobs would not be deployed, since this task file would not run for those. And due to the scoping for controller nodes only it would never do. My controllers are not meant for computing only for job start, hence they have no GPUs. Compute nodes are not accessible for the users unless they have an actual job running (on the particular node(s)), but that is deployed in compute.yml.

Hmm, maybe I was mislead by the naming of that task file ;-)

Thanks for clarifying.

**Comment by avolkov1** [comment]
If you setup with a separate controller as one should setup SLURM, then login-compute-setup.yml should not be used at all (do not set `slurm_login_on_compute` in `config/group_vars/slurm-cluster.yml`) as it is meant for a special single node setup (docs/slurm-cluster/slurm-single-node.md) or in cases where you don't have a separate controller node. Refer to
playbooks/slurm-cluster/slurm.yml
```
# Set up slurm-login-on-compute if enabled
- hosts: slurm-master
  become: yes
  tasks:
    - name: Setup slurm login on compute if enabled.
      include_role:
        name: slurm
        tasks_from: login-compute-setup
      vars:
        user: "{{ ansible_env.SUDO_USER | default(ansible_env.USER) }}"
        is_controller: yes
      when: slurm_login_on_compute | default(false)
```

For "compute nodes are not accessible for the users unless they have an actual job running", that's setup via pam_slurm_adopt in `roles/slurm/tasks/compute.yml`.
