### ISSUE TITLE
SLURM Installation: ansible-playbook picks wrong python interpreter

### ISSUE THREAD

**Issue by mfruhner** [NVIDIA/deepops#1237]
Hello, I am following the single node installation for SLURM guide, but I am running into many problems.
Some I could fix myself.

I am trying to install SLURM onto a DGX-Station (DGX OS 5.4).

After having two problems with kubespray, which I could workaround I am now seeing this:

```
TASK [standalone-container-registry : install python-docker] ****
fatal: [dgxstation]: FAILED! => changed=false
  msg: No package matching 'python-docker' is available
```

which I don't quite understand. I am using python 3.8, but [the .yaml file](https://github.com/NVIDIA/deepops/blob/6eb1ca464a303766d50713871a6ba7156648d062/roles/standalone-container-registry/tasks/main.yml) defines that this package should only be installed when using python 2.7:

```yaml
- name: Ensure Python 2 dependencies are installed via OS packages
  when: (ansible_python.version.major==2) and (ansible_python.version.minor==7)
  block:
  - name: install python-docker
    package:
      name: python-docker
```

Running `pip install python-docker` manually also works inside the newly created python env.

Could you help me here?
Thanks!

```
ansible [core 2.11.12]
  config file = /home/maik/deepops/ansible.cfg
  configured module search path = ['/home/maik/deepops/submodules/kubespray/library']
  ansible python module location = /opt/deepops/env/lib/python3.8/site-packages/ansible
  ansible collection location = /home/maik/deepops/collections
  executable location = /opt/deepops/env/bin/ansible
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
  jinja version = 2.11.3
  libyaml = True
```
