### ISSUE TITLE
GPU is disassociating after running a playbook

### ISSUE THREAD

**Issue by georgettica** [NVIDIA/deepops#1246]
I ran a playbook with 
```
  ---
  - hosts: all
    gather_facts: False
    tasks:
    - name: Run Role
      ansible.builtin.include_role: ...
```

some of the containers on a node (running via slurm) are getting an NVML Error.

I thought it might be because of the /etc/ansible/facts.d/*, but it didn't happen.

the Role I am running is copying files to the host, and running `systemctl restart <SVC> && systemctl enable <SVC>` using a playbook.

If you would like additional logs I would gladly sanitize and send to you
