### ISSUE TITLE
Error mounting /home: umount: /home: target is busy

### ISSUE THREAD

**Issue by starlitsky2010** [NVIDIA/deepops#1273]
Hello, I met the similar error:
My system is Ubuntu 20.04
Slurm Controller Server / login Node: Server without NVIDIA graphic card
GPU Node 0 :  A100 * 8
Running install script Server: Server without NVIDIA graphic card

I'm using nfs_exports and nfs_mounts as follows:

```
# Default exports:
# - /home: shared home directories, needed for Open OnDemand and best practice
# - /sw:   shared space for software installs, used for Spack or EasyBuild
nfs_exports:
  - path: /home
    options: "*(rw,sync,no_root_squash)"
  - path: /sw
    options: "*(rw,sync,no_root_squash)"
nfs_mounts:
  - mountpoint: /home
    server: '{{ groups["slurm-master"][0] }}'
    path: /home
    options: async,vers=3
  - mountpoint: /sw
    server: '{{ groups["slurm-master"][0] }}'
    path: /sw
    options: async,vers=3

https://github.com/NVIDIA/deepops.git with baseline commit id:
7fb8f2c6662c307463d03e87b994da4b6932ba0d

```

The error logs:
```
TASK [nfs : ensure mountpoint exists] ********************************************************************************************************************************************************
ok: [gpu01] => (item={'mountpoint': '/home', 'server': 'login01', 'path': '/home', 'options': 'async,vers=3'})
ok: [gpu01] => (item={'mountpoint': '/sw', 'server': 'login01', 'path': '/sw', 'options': 'async,vers=3'})

TASK [nfs : configure /etc/fstab on clients] *************************************************************************************************************************************************
failed: [gpu01] (item={'mountpoint': '/home', 'server': 'login01', 'path': '/home', 'options': 'async,vers=3'}) => changed=false 
  ansible_loop_var: item
  item:
    mountpoint: /home
    options: async,vers=3
    path: /home
    server: login01
  msg: |-
    Error mounting /home: umount: /home: target is busy.
ok: [gpu01] => (item={'mountpoint': '/sw', 'server': 'login01', 'path': '/sw', 'options': 'async,vers=3'})
```

I've also tried sudo apt-get install nfs-kernel-server but failed

I've also tried the following methods:

$ fuser -mk /home
$ cd /
user@gpu01:/$ sudo umount -lf /home
umount: /home: not mounted.
user@gpu01:/$ fuser -mv /home
```
                     USER        PID ACCESS COMMAND
/home:               root     kernel mount /home
                     user        47024 .rce. systemd
                     user        47246 .rce. bash
```
It looks like mounted by kernel.
How can I solve this problem?

_Originally posted by @starlitsky2010 in https://github.com/NVIDIA/deepops/issues/939#issuecomment-1574992056_
