### ISSUE TITLE
no token generate with ./scripts/k8s/deploy_dashboard_user.sh

### ISSUE THREAD

**Issue by Steven9Smith** [NVIDIA/deepops#1284]
This is an issue since they changed how tokens work in the new kubeterntes.
I'm running the lastes version of deepops (as of the date this is posted) from a clean install. after starting the dashboard no token was generated. after some reasearch it seems the token generation has changed. to fix this you need to update the file:

workloads/services/k8s/k8s-dashboard-admin.yml

to

```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user
  namespace: kube-system
---
apiVersion: v1
kind: Secret
metadata:
  name: admin-user-secret
  annotations:
    kubernetes.io/service-account.name: admin-user
  namespace: kube-system
type: kubernetes.io/service-account-token

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: admin-user
  namespace: kube-system
```

apply the changes:

`kubectl apply -f workloads/services/k8s/k8s-dashboard-admin.yml`

then you can deploy the dashboard again or type
`kubectl -n kube-system describe secret admin-user-secret`
