### ISSUE TITLE
NFS service configuration should be saved in the config directory

### ISSUE THREAD

**Issue by supertetelman** [NVIDIA/deepops#322]
The ./services/nfs-client.yml file currently requires users to modify ports/ips/directories.

It would be good if we moved this information from the service file into a configuration file.

```
ubuntu@mgmt1:~/deepops$ cat services/nfs-client.yml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data
spec:
  capacity:
    storage: 2000Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.100
    path: "/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 2000Gi
```
