### ISSUE TITLE
Integrate Prometheus with pod-gpu-metrics-exporter

### ISSUE THREAD

**Issue by supertetelman** [NVIDIA/deepops#395]
**What:**
We currently include the node-exporter in DeepOps, but not the pod-gpu-metrics exporter. It would be good if we could include the pod-level metrics in prometheus and Grafana as well. If not Grafana, at least Prometheus.

**Why:**
Many DeepOps users are looking to use the metrics from pods to determine how many resources were used by a project/user in a specific namespace, for a job, or deployments. Getting the pod level metrics would enable people to build chargeback systems, look jobs that are using too much/little resources, etc.

**How:**
This can be setup on a DeepOps cluster with a few kubectl commands. We should create a new DeepOps role to get this working. Maybe later we push the role back upstream to the monitoring project.

**Example output:**
![image](https://user-images.githubusercontent.com/1010167/71034229-d01a7200-20cd-11ea-8ecc-e9003530edcc.png)

**Documentation here:**
https://github.com/NVIDIA/gpu-monitoring-tools/tree/master/exporters/prometheus-dcgm/k8s/pod-gpu-metrics-exporter

**Comment by yug0slav** [comment]
I have been playing around with CoreOS / kube-prometheus (https://github.com/coreos/kube-prometheus) and pod-gpu-metrics-exporter on top of it (https://github.com/NVIDIA/gpu-monitoring-tools/tree/master/exporters/prometheus-dcgm/k8s/pod-gpu-metrics-exporter)

Added node:9400 targets to Prometheus additional scrape config 
```
- job_name: gpu_metrics
  scrape_interval: 5s
  metrics_path: /gpu/metrics
  scheme: http
  static_configs:
  - targets: ['node1:9400']
    labels:
      node: 'node1'
  - targets: ['node2:9400']
    labels:
      node: 'node2'
```

Added dcgm per pod metrics to Grafana namespace(pod) kube-prometheus dashboard.
