### ISSUE TITLE
GPU Operator Support

### ISSUE THREAD

**Issue by rmccorm4** [NVIDIA/deepops#397]
In order to support the GPU Operator as an easy way of spinning up GPU nodes with variable driver versions in a K8s cluster on the fly, I'd like to propose the ability to de-couple NVIDIA GPU components from the K8s cluster setup per the GPU Operator's requirements: https://github.com/NVIDIA/gpu-operator

I think the `playbooks/k8s-cluster.yml`'s default functionality can remain as is, but I would like to see how we can ignore NVIDIA components via flags, tags, or config variables for flexibility.

Personally I would think adding more `nvidia` tags into certain parts of playbook and then using `--skip-tags "nvidia"` when running the playbook would be the simplest solution, but I don't know enough to know if that would work out of the box or not. 

I'm happy to discuss, as well as contribute once we have a good approach 🙂

**Comment by supertetelman** [comment]
As far as I can tell, the only pieces in the `k8s-cluster.yml` playbook that have to do with NVIDIA components are:

```
# Install driver and container runtime on GPU servers
- include: nvidia-driver.yml
  tags:
    - nvidia
- include: nvidia-docker.yml
  tags:
    - nvidia

# Install k8s GPU device plugin
- include: k8s-gpu-plugin.yml
```

We could just wrap those three includes in a block to skip with the `skip-nvidia` flag.
