### ISSUE TITLE
Virtual DeepOps - dgx01 final reboot with no IP address

### ISSUE THREAD

**Issue by yoeljacobsen** [NVIDIA/deepops#42]
With virtual deployment, the deployment fails as the dgx01 VM final reboot leaves it without an IP address.

The problem is /etc/network/interfaces specifying the address for eth1, but there is no such interface (only enp6..).

I fixed it by adding `net.ifnames=0` to the kernel in ansible/roles/slurm/tasks/compute.yml:
```
- name: add cgroups to grub options
  lineinfile:
    dest: /etc/default/grub
    regexp: "^GRUB_CMDLINE_LINUX="
    line: 'GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1 net.ifnames=0"'
  register: update_grub
```
