### ISSUE TITLE
The error was: list object has no element 0 in "install GPU operator helm chart task"

### ISSUE THREAD

**Issue by ReyRen** [NVIDIA/deepops#517]
Hello, 

When I use GPU-operator to manage GPU driver installation, an error `The task includes an option with an undefined variable. The error was: list object has no element 0` occurred in `TASK [nvidia-gpu-operator : install GPU operator helm chart`
```
# GPU operator
- hosts: kube-master
  become: yes
  tasks:
    - name: Install helm chart for GPU operator (Ubuntu)
      include_role:
        name: nvidia-gpu-operator
      vars:
        tiller_host: "{{ tiller_service_ubuntu.resources[0].spec.clusterIP }}"
      run_once: true
      when: ansible_distribution == "Ubuntu"
```
When I track the `tiller_service_ubuntu.resources`
```
# Register Tiller service info
- hosts: kube-master
  become: true
  tasks:
    - name: Get tiller service info (Ubuntu)
      k8s_facts:
        api_version: v1
        kind: Service
        name: tiller-deploy
        namespace: kube-system
      environment:
        PYTHONHOME: "{{ deepops_venv }}"
      register: tiller_service_ubuntu
      when: ansible_distribution == "Ubuntu"
```
the output is:
```
ok: [master] => changed=false
  invocation:
    module_args:
      api_key: null
      api_version: v1
      ca_cert: null
      client_cert: null
      client_key: null
      context: null
      field_selectors: []
      host: null
      kind: Service
      kubeconfig: null
      label_selectors: []
      name: tiller-deploy
      namespace: kube-system
      password: null
      proxy: null
      username: null
      validate_certs: null
  resources: []
```
obviously the resource[] is empty

Is there I miss someting?

Really appreciate if you can give me a hint

Thanks
