### ISSUE TITLE
Create an example configurations for Kubeflow MIG integration

### ISSUE THREAD

**Issue by supertetelman** [NVIDIA/deepops#671]
People who are using Kubeflow will want to use MIG when doing Jupyter Notebook development. We should buiild this capability into the script or provide an example configuration until something more official is available in Kubeflow or through the other GPU tooling.

This can be achieved by modifying `jupyter-web-app/overlays/aws/config-map.yaml` and `kustomize/jupyter-web-app/base/configs/spawner_ui_config.yaml` before running the `kfctl apply command. The changes should look something like this, depending on the cluster configuration:
```
  gpus:
    # Number of GPUs to be assigned to the Notebook Container
    value:
      # values: "none", "1", "2", "4", "8"
      num: "none"
      # Determines what the UI will show and send to the backend
      vendors:
        - limitsKey: "nvidia.com/mig-7g.40gb"
          uiName: "NVIDIA MIG - 7g.40gb"
        - limitsKey: "nvidia.com/mig-4g.20gb"
          uiName: "NVIDIA MIG - 4g.20gb"
        - limitsKey: "nvidia.com/mig-3g.20gb"
          uiName: "NVIDIA MIG - 3g.20gb"
        - limitsKey: "nvidia.com/mig-2g.10gb"
          uiName: "NVIDIA MIG - 2g.10gb"
        - limitsKey: "nvidia.com/mig-1g.5gb"
          uiName: "NVIDIA MIG - 1g.5gb"
      # Values: "" or a `limits-key` from the vendors list
      vendor: ""
    readOnly: false
```
This will result in a drop down in the notebook page to select any of these resources. It will not help during training.

This would work for a 1A00 only cluster. However, a mixed cluster with A100 and other GPU types would run into issues when using nvidia.com/gpu resources. To accomodate this we will also need to use NodeSelectors, a built-in feature coming soon to Kubeflow (https://github.com/kubeflow/kubeflow/pull/5237).
