### ISSUE TITLE
Create an example configuration for setting up Kubeflow NodeAffinity profiles to support heterogenous clusters

### ISSUE THREAD

**Issue by supertetelman** [NVIDIA/deepops#938]
With the Kubeflow 1.2 release, Notebook deployments can now use NodeAffinity to select execution nodes. With this feature we can now suppoer heterogeneous clusters of mixed GPU types. In order for this feature to work, several profiles need to be added to the Kubeflow config.

We should create some example Kubeflow configuration files that leverage the GPU Feature Discover labels and allow easy selection of A100, V100, T4, MIG, etc.

It may even be a good idea to add his configuration to the default DeepOps Kubeflow install. Although, I would not necessarily be able to commit to testing and supporting this feature going forward.

Related to https://github.com/NVIDIA/deepops/issues/671.

Here is an example configuration from Kubeflow issue 5273.

```
spawnerFormDefaults:
  ...
  affinityConfig:
    # The default `configKey` from the options list
    # If readonly, the default value will be the only option
    value: "none"
    # The list of available affinity configs
    options:
      - configKey: "none"
        displayName: "None"
        affinity: {}
      # (DESC) Pod gets an exclusive "n1-standard-2" Node
      # (TIP) set PreferNoSchedule taint on this node-pool
      # (TIP) enable cluster-autoscaler on this node-pool
      # (TIP) dont let users request more CPU/MEMORY than the size of this node
      - configKey: "exclusive__n1-standard-2"
        displayName: "Exclusive: n1-standard-2"
        affinity:
          # (Require) Node having label: `node_pool=notebook-n1-standard-2`
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: "node_pool"
                      operator: "In"
                      values:
                        - "notebook-n1-standard-2"
          # (Require) Node WITHOUT existing Pod having label: `notebook-name`
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: "notebook-name"
                      operator: "Exists"
                namespaces: []
                topologyKey: "kubernetes.io/hostname"
    readOnly: false
  tolerationGroup:
    # The default `groupKey` from the options list
    # If readonly, the default value will be the only option
    value: "none"
    # The list of available tolerationGroup configs
    options:
      - groupKey: "none"
        displayName: "None"
        tolerations: []
      - groupKey: "group_1"
        displayName: "Group 1: description"
        tolerations:
          - key: "key1"
            operator: "Equal"
            value: "value1"
            effect: "NoSchedule"
          - key: "key2"
            operator: "Equal"
            value: "value2"
            effect: "NoSchedule"
    readOnly: false
```
