### ISSUE TITLE
NFS client error

### ISSUE THREAD

**Issue by verdurin** [NVIDIA/deepops#939]
Just tried setting up a Slurm cluster, nodes of which are all running CentOS 7.

Here's the error I saw:
```
TASK [nfs : configure /etc/fstab on clients] *******************************************************************************************************************************************************************************************************************************
failed: [gpu01] (item={'mountpoint': '/home', 'server': 'login01', 'path': '/home', 'options': 'async,vers=3'}) => changed=false
  ansible_loop_var: item
  item:
    mountpoint: /home
    options: async,vers=3
    path: /home
    server: login01
  msg: |-
    Error mounting /home: mount.nfs: requested NFS version or transport protocol is not supported
failed: [gpu01] (item={'mountpoint': '/sw', 'server': 'login01', 'path': '/sw', 'options': 'async,vers=3'}) => changed=false
  ansible_loop_var: item
  item:
    mountpoint: /sw
    options: async,vers=3
    path: /sw
    server: login01
  msg: |-
    Error mounting /sw: mount.nfs: requested NFS version or transport protocol is not supported
    ```

**Comment by ajdecon** [comment]
I can't currently reproduce this. Closing, but feel free to reopen if you're still seeing this with 21.06.

If you still see this, please provide the configuration you're using for the `nfs_exports` and `nfs_mounts` variables.

**Comment by DTDwind** [comment]
Hello, I get this error same.

my system version is `Ubuntu  20.04.1`

my NAS is `synology 7.1-42661`

I  using for the nfs_exports and nfs_mounts is that.

```
nfs_exports:
  - path: /home
    options: "*(rw,sync,no_root_squash)"
  - path: /sw
    options: "*(rw,sync,no_root_squash)"
nfs_mounts:
  - mountpoint: /home
    server: '{{ groups["slurm-master"][0] }}'
    path: /home
    options: async,vers=3
  - mountpoint: /sw
    server: '{{ groups["slurm-master"][0] }}'
    path: /sw
    options: async,vers=3
```

![error](https://user-images.githubusercontent.com/22238266/210200465-56360d6b-071f-4619-a9e3-a92834338fe3.png)

Anyone can give me some help?

**Comment by DTDwind** [comment]
Solved.
Need to do `sudo apt-get install nfs-kernel-server`

**Comment by starlitsky2010** [comment]
Hello, I met the similar error:
My system is Ubuntu 20.04
Slurm Controller Server / login Node: Server without NVIDIA graphic card
GPU Node 0 :  A100 * 8
Running install script Server: Server without NVIDIA graphic card

I'm using nfs_exports and nfs_mounts as follows:
################################################################################
# NFS                                                                          #
################################################################################
# Default exports:
# - /home: shared home directories, needed for Open OnDemand and best practice
# - /sw:   shared space for software installs, used for Spack or EasyBuild
nfs_exports:
  - path: /home
    options: "*(rw,sync,no_root_squash)"
  - path: /sw
    options: "*(rw,sync,no_root_squash)"
nfs_mounts:
  - mountpoint: /home
    server: '{{ groups["slurm-master"][0] }}'
    path: /home
    options: async,vers=3
  - mountpoint: /sw
    server: '{{ groups["slurm-master"][0] }}'
    path: /sw
    options: async,vers=3

https://github.com/NVIDIA/deepops.git with baseline commit id:
7fb8f2c6662c307463d03e87b994da4b6932ba0d

The error logs:
TASK [nfs : ensure mountpoint exists] ********************************************************************************************************************************************************
ok: [gpu01] => (item={'mountpoint': '/home', 'server': 'login01', 'path': '/home', 'options': 'async,vers=3'})
ok: [gpu01] => (item={'mountpoint': '/sw', 'server': 'login01', 'path': '/sw', 'options': 'async,vers=3'})

TASK [nfs : configure /etc/fstab on clients] *************************************************************************************************************************************************
failed: [gpu01] (item={'mountpoint': '/home', 'server': 'login01', 'path': '/home', 'options': 'async,vers=3'}) => changed=false 
  ansible_loop_var: item
  item:
    mountpoint: /home
    options: async,vers=3
    path: /home
    server: login01
  msg: |-
    Error mounting /home: umount: /home: target is busy.
ok: [gpu01] => (item={'mountpoint': '/sw', 'server': 'login01', 'path': '/sw', 'options': 'async,vers=3'})

It's really hard to solve. I've also tried sudo apt-get install nfs-kernel-server but failed

**Comment by starlitsky2010** [comment]
![image](https://github.com/NVIDIA/deepops/assets/10757117/1e27496c-45fc-46fb-b428-f7bbf2082c3c)

**Comment by DTDwind** [comment]
Try this
```
nfs_exports:
  - path: /slurm/home
    options: "*(rw,sync,no_root_squash)"
  - path: /sw
    options: "*(rw,sync,no_root_squash)"
nfs_mounts:
  - mountpoint: /slurm/home
    server: '{{ groups["slurm-nfs"][0] }}'
    path: /volume1/share     # the path in NAS
    options: async,vers=3
  - mountpoint: /sw
    server: '{{ groups["slurm-nfs"][0] }}'
    path: /volume1/sw        # the path in NAS
    options: async,vers=3
```
